# Generated by Django 5.2.4 on 2025-07-31 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=255)),
                ('shipping_district', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='order.order')),
            ],
        ),
    ]
